site: Imaginative World
title: Be Imaginative
description: >-
  Just another weblog by Md. Mahmudul Hasan Shohag.
lang: en-US
timezone: Dhaka
repo: https://github.com/ImaginativeShohag/imaginativeshohag.github.io # site repo [optional]
data-theme: dark # default theme "dark" | "light"

author:
  name: Md. Mahmudul Hasan Shohag
  bio: Software Engineer, Enjoying to the fullest.
  username: ImaginativeShohag
  github: ImaginativeShohag
  twitter: shohag_iw
  email: imaginativeshohag@email.com

# URL settings
domain: imaginativeshohag.github.io
url: https://imaginativeshohag.github.io
baseurl: "" # leave blank if not wished
permalink: "https://imaginativeshohag.github.io/"

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - .jekyll-cache
  - .obsidian
  - src
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  - package.json
  - package-lock.json
  - postcss.config.js
  - tailwind.config.js
  - .gitignore
  - node_modules
  - yarn.lock
  - src

compress_html:
  clippings: all
  comments: [ "<!-- ", " -->" ]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug

defaults:
  - scope:
      path: ""
    values:
      layout: "default.liquid"
  - scope:
      path: ""
    values:
      layout: "default.liquid"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page.liquid"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post.liquid"

relative_links:
  enabled: true
  collections: false


