site: Imaginative World
title: Imaginative World
description: >-
  Just another weblog by Md. Mahmudul Hasan Shohag.
lang: en-US
timezone: Asia/Dhaka
repo: https://github.com/ImaginativeShohag/imaginativeshohag.github.io # site repo [optional]
data-theme: dark # default theme "dark" | "light"

author:
  name: Md. Mahmudul Hasan Shohag
  bio: Software Engineer, Enjoying to the fullest.
  avatar: https://imaginativeshohag.github.io/assets/image/me.png
  url: https://imaginativeshohag.github.io
  username: ImaginativeShohag
  github: ImaginativeShohag
  twitter: shohag_iw
  email: imaginativeshohag@gmail.com

# Jekyll SEO Tag
twitter:
  username: shohag_iw
  card: summary

facebook:
  publisher: https://www.facebook.com/Imaginative.World.BD
  admins: https://www.facebook.com/imaginativeshohag

social:
  name: Md. Mahmudul Hasan Shohag
  links:
    - https://twitter.com/shohag_iw
    - https://www.facebook.com/imaginativeshohag
    - https://www.linkedin.com/in/mahmudulhasanshohag
    - https://github.com/imaginativeshohag

# URL settings
domain: imaginativeshohag.github.io
url: https://imaginativeshohag.github.io
baseurl: "" # leave blank if not wished
permalink: https://imaginativeshohag.github.io/

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - .jekyll-cache
  - .sass-cache
  - .obsidian
  - .idea
  - src
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  - package.json
  - package-lock.json
  - postcss.config.js
  - tailwind.config.js
  - .gitignore
  - node_modules
  - yarn.lock
  - src
  - LICENSE
  - utils

compress_html:
  clippings: all
  comments: [ "<!-- ", " -->" ]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
  - jekyll-seo-tag

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug

defaults:
  - scope:
      path: ""
    values:
      layout: "default.liquid"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page.liquid"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post.liquid"

post_types:
  standard: "standard"
  link: "link"
  quote: "quote"

relative_links:
  enabled: true
  collections: false


